name: mycompass_admin_website
description: "A mycompass_admin_website."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  charts_flutter_new: ^0.12.0
  data_table_2: ^2.5.16
  flutter_svg: ^2.0.16
  provider: ^6.1.2
  fl_chart: ^0.69.2
  iconsax: ^0.0.8
  page_transition: ^2.1.0
  dynamic_path_url_strategy: ^1.0.0
  file_picker: ^8.1.7
  image_picker: ^1.1.2
  flutter_bloc: ^9.0.0
  dio: ^5.7.0
  shared_preferences: ^2.3.5
  modal_progress_hud_nsn: ^0.5.1
  mime: ^2.0.0
  http_parser: ^4.0.2
#  intl: ^0.17.0
  photo_view: ^0.15.0
  socket_io_client: ^3.0.2
  awesome_notifications: ^0.7.4+1
  flutter_localizations:
    sdk: flutter
  intl: any



dependency_overrides:
  intl: 0.19.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - lang/de.json
    - lang/en.json
